spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/jdbcDemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid:
      #filters: stat,wall,log4j


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.etrans.jdbc.pojo